### ISSUE TITLE
Please add me to the org

### ISSUE THREAD

**Issue by bitops** [ModernAppsNinja/dojo#2]
This request can only be used for the github account the user making the request is logged into. 

After submitting this request, the github user account that submitted this request will be reviewed for membership, please allow a few days for processing. 

The Secret Passphrase is "I am Not a Robot"

**You must enter the secret passphrase where indicated below for this request to be considered**

Secret Passphrase: I am Not a Robot

**Comment by modernappsninja-owners** [comment]
@bitops Sorry for my delay! I added you to the org, you should now see an invitation in the email address associated with your github account.

Please consider joining a ModernApps Ninja working group, you can see more info here: https://github.com/ModernAppsNinja/Projects/tree/master/WorkingGroups

Thanks so much!
