### ISSUE TITLE
SE Based in Singapore

### ISSUE THREAD

**Issue by yogendra** [ModernAppsNinja/dojo#5]
This request can only be used for the github account the user making the request is logged into. 

After submitting this request, the github user account that submitted this request will be reviewed for membership, please allow a few days for processing. 

The Secret Passphrase is "I am Not a Robot"

**You must enter the secret passphrase where indicated below for this request to be considered**

Secret Passphrase: I am Not a Robot

**Comment by afewellvmware** [comment]
Hi @yogendra I have added you to the modernapps ninja org, please check the email associated with your github account to find and accept the invitation. 

Thanks!
