### ISSUE TITLE
VMware SE - Request to join ModernApps Ninja Github Org

### ISSUE THREAD

**Issue by mqamorim** [ModernAppsNinja/dojo#8]
This request can only be used for the github account the user making the request is logged into. 

After submitting this request, the github user account that submitted this request will be reviewed for membership, please allow a few days for processing. 

The Secret Passphrase is "I am Not a Robot"

**You must enter the secret passphrase where indicated below for this request to be considered**

Secret Passphrase: I am Not a Robot

**Comment by afewellvmware** [comment]
@mqamorim So sorry for my delayed response, I accidentally set alerts for this repo to the wrong inbox so missed seeing this. 

I added you to the org so please check the email address associated with your github account as you will need to accept the invitation before it is confirmed. 

Thanks!
